feat: add server stats endpoint and minor fixes
Signed-off-by: Atul Kadian <atul2143143@gmail.com>

diff --git a/.husky/pre-commit b/.husky/pre-commit
--- a/.husky/pre-commit
+++ b/.husky/pre-commit
@@ -1,1 +1,3 @@
-pnpm lint
+echo "🚨 Zero Trust Policy enabled 🗿. Checking for build errors before committing 🛠️"
+pnpm build | grep -q "error" && echo "❌ Build failed. Please fix the errors before committing 🙂" && exit 1
+echo "✅ Build successful. Committing changes 🚀"
